# Semana 9 — Lista de Prática SQL para Data Warehouse

Este notebook contém **10 exercícios progressivos** para praticar os conteúdos da Semana 9 usando o mesmo modelo de dados trabalhado em aula.

## Conteúdos praticados

- `SELECT`, `WHERE`, `ORDER BY` e `LIMIT`
- `INNER JOIN` entre fato e dimensões
- `LEFT JOIN`
- `GROUP BY`, `SUM`, `COUNT` e `AVG`
- `WHERE` antes da agregação
- `HAVING` depois da agregação
- `DATE_TRUNC` e `EXTRACT`

## Tabelas usadas

- `fato_vendas`: tabela fato com as vendas
- `dim_cliente`: dimensão com cidade e estado do cliente
- `dim_produto`: dimensão com categoria do produto
- `dim_tempo`: dimensão com datas, ano, mês, trimestre e ano/mês

> Orientação: escreva sua resposta dentro da célula de código de cada exercício, substituindo o comentário `-- escreva sua consulta aqui`.

## 1. Preparação do ambiente

Execute as células abaixo antes de iniciar os exercícios. Os arquivos `.csv` devem estar na mesma pasta deste notebook. Caso estejam em outra pasta, altere o valor da variável `BASE_PATH`.

In [2]:
# Instalação, caso esteja usando Google Colab ou ambiente sem DuckDB
# !pip install duckdb pandas

In [15]:
import pandas as pd
import duckdb
from pathlib import Path

# Altere aqui se os arquivos estiverem em outra pasta
BASE_PATH = Path('../Dataset_schema')

dim_cliente = pd.read_csv(BASE_PATH / 'dim_cliente.csv')
dim_produto = pd.read_csv(BASE_PATH / 'dim_produto.csv')
dim_tempo = pd.read_csv(BASE_PATH / 'dim_tempo.csv')
fato_vendas = pd.read_csv(BASE_PATH / 'fato_vendas.csv')

banco_dados = duckdb.connect()
banco_dados.register('dim_cliente', dim_cliente)
banco_dados.register('dim_produto', dim_produto)
banco_dados.register('dim_tempo', dim_tempo)
banco_dados.register('fato_vendas', fato_vendas)

print('Tabelas carregadas com sucesso!')

Tabelas carregadas com sucesso!

## 2. Consulta rápida das tabelas

Use esta parte para lembrar quais colunas existem em cada tabela.

In [4]:
print('fato_vendas')
display(fato_vendas.head(1))

print('dim_cliente')
display(dim_cliente.head(1))

print('dim_produto')
display(dim_produto.head(1))

print('dim_tempo')
display(dim_tempo.head(1))

fato_vendas

,venda_sk,order_id,order_item_id,cliente_sk,produto_sk,tempo_sk,valor_produto,valor_frete,valor_total
0,1,00010242fe8c5a6d1ba2dd792cb16214,1,65558,25866,64,58.9,13.29,72.19

dim_cliente

,cliente_sk,customer_id,customer_unique_id,customer_city,customer_state
0,1,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,franca,SP

dim_produto

,produto_sk,product_id,product_category_name,product_category_name_english
0,1,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,perfumery

dim_tempo

   tempo_sk        data   ano  mes  dia  trimestre  ano_mes
0         1  2017-10-02  2017   10    2          4  2017-10

# 10 exercícios de prática

## Exercício 1 🟢 — Primeiras vendas da tabela fato

Liste as **20 primeiras vendas** da tabela `fato_vendas`.

Mostre as colunas:

- `venda_sk`
- `order_id`
- `valor_produto`
- `valor_frete`
- `valor_total`

**Objetivo:** praticar `SELECT`, `FROM` e `LIMIT`.

In [16]:
banco_dados.sql("""
    SELECT
        venda_sk,
        order_id,
        valor_produto,
        valor_frete,
        valor_total
    FROM fato_vendas
    LIMIT 20;
""").df()

,venda_sk,order_id,valor_produto,valor_frete,valor_total
0,1,00010242fe8c5a6d1ba2dd792cb16214,58.90,13.29,72.19
1,2,00018f77f2f0320c557190d7a144bdd3,239.90,19.93,259.83
2,3,000229ec398224ef6ca0657da4fc703e,199.00,17.87,216.87
3,4,00024acbcdf0a6daa1e931b038114c75,12.99,12.79,25.78
4,5,00042b26cf59d7ce69dfabb4e55b4fd9,199.90,18.14,218.04
5,6,00048cc3ae777c65dbb7d2a0634bc1ea,21.90,12.69,34.59
6,7,00054e8431b9d7675808bcb819fb4a32,19.90,11.85,31.75
7,8,000576fe39319847cbb9d288c5617fa6,810.00,70.75,880.75
8,9,0005a1a1728c9d785b8e2b08b904576c,145.95,11.65,157.60
9,10,0005f50442cb953dcd1d21e1fb923495,53.99,11.40,65.39
10,11,00061f2a7bc09da83e415a52dc8a4af1,59.99,8.88,68.87
11,12,00063b381e2406b52ad429470734ebd5,45.00,12.98,57.98
12,13,0006ec9db01a64e59a68b2c340bf65a7,74.00,23.32,97.32
13,14,0008288aa423d2a3f00fcb17cd7d8719,49.90,13.37,63.27
14,15,0008288aa423d2a3f00fcb17cd7d8719,49.90,13.37,63.27
15,16,0009792311464db532ff765bf7b182ae,99.90,27.65,127.55
16,17,0009c9a17f916a706d71784483a5d643,639.00,11.34,650.34
17,18,000aed2e25dbad2f9ddb70584c5a2ded,144.00,8.77,152.77
18,19,000c3e6612759851cc3cbb4b83257986,99.00,13.71,112.71
19,20,000e562887b1f2006d75e0be9558292e,25.00,16.11,41.11

## Exercício 2 🟢 — Filtro com WHERE

Liste as vendas em que o `valor_total` seja **maior que 300**.

Mostre as colunas:

- `venda_sk`
- `order_id`
- `valor_total`

Ordene o resultado do **maior para o menor valor total**.

**Objetivo:** praticar `WHERE` e `ORDER BY DESC`.

In [6]:
banco_dados.sql("""
    SELECT
        venda_sk,
        order_id,
        valor_total
    FROM fato_vendas
    WHERE valor_total > 300    
    ORDER BY valor_total DESC;
""").df()

      venda_sk                          order_id  valor_total
0         3482  0812eb902a67711a1cb742b3cdaa65ae      6929.31
1       109785  fefacc66af859508bf1a7934eab1e97f      6922.21
2       105496  f5136e38d1a14a4dbd87dff67da82701      6726.66
3        72721  a96610ab360d42a2e5335a3998b4718a      4950.34
4        10998  199af31afc78c699f0dbf71fb178d4d4      4764.34
...        ...                               ...          ...
8498     17744  299ad5e33a5f4fe1efcac35b99b0fad8       300.21
8499    105349  f4ae2ab52b8c6e093b06d6656ee4d351       300.12
8500     11827  1b6c00256bc49004b1d059039306c08e       300.12
8501     25863  3c38b53bb7d6f3c9f00d993a80f8cdd5       300.11
8502     22861  3551cfc89b9792b082608627a57d6bc2       300.06

[8503 rows x 3 columns]

## Exercício 3 🟢 — Ranking de fretes

Liste as **15 vendas com maior valor de frete**.

Mostre as colunas:

- `venda_sk`
- `order_id`
- `valor_frete`
- `valor_total`

**Objetivo:** praticar ordenação e criação de ranking com `ORDER BY` e `LIMIT`.

In [7]:
banco_dados.sql("""
    SELECT
        venda_sk,
        order_id,
        valor_frete,
        valor_total
    FROM fato_vendas
    ORDER BY valor_frete DESC
    LIMIT 15;
""").df()

    venda_sk                          order_id  valor_frete  valor_total
0      71885  a77e1550db865202c56b19ddc6dc4d53       409.68      1388.68
1       3232  076d1555fb53a89b0ef4d529e527a0f6       375.28      2713.36
2      27413  3fde74c28a3d5d618c00f26d51baafa0       375.28      2713.36
3      68275  9f49bd16053df810384e793386312674       339.59      1488.59
4      16360  264a7e199467906c0727394df82d1a6a       338.30      1388.30
5      86056  c7a07ddd52bbe18b61da49a8d89853d3       322.10      1372.10
6       4939  0b6230647ed16f4b3e70282dc4b5b87f       321.88      1371.88
7       3510  0822bcde10bb5d023755a71bc8f7797f       321.46      1311.46
8      29114  43bdbd9dc0931d72befdf4765af6c442       317.47      3406.47
9      47246  6ddfbf514959b49b6410c01ad93054bb       314.40      1359.40
10      6144  0e4672661531addf3fa0f55961e55242       314.02      1304.02
11    109411  fe12e676fd493885d417a34bc3917411       312.41      1072.41
12     26572  3dd5626c63f493f8b8f8788c2be24baa       306.06      3005.06
13     89357  cf4659487be50c0c317cff3564c4a840       299.16       474.16
14     89358  cf4659487be50c0c317cff3564c4a840       299.16       474.16

## Exercício 4 🟡 — INNER JOIN com clientes

Mostre as vendas junto com o **estado e a cidade do cliente**.

Use `INNER JOIN` entre `fato_vendas` e `dim_cliente`.

Mostre as colunas:

- `f.venda_sk`
- `f.order_id`
- `c.customer_city`
- `c.customer_state`
- `f.valor_total`

Mostre apenas 20 linhas.

**Objetivo:** praticar relacionamento entre tabela fato e dimensão cliente.

In [8]:
banco_dados.sql("""
SELECT
    f.venda_sk,
    f.order_id,
    c.customer_city AS Cidade,
    c.customer_state AS Estado,
    f.valor_total
FROM fato_vendas f
INNER JOIN dim_cliente c
    ON f.cliente_sk = c.cliente_sk
LIMIT 20;
""").df()

,venda_sk,order_id,Cidade,Estado,valor_total
0,1,00010242fe8c5a6d1ba2dd792cb16214,campos dos goytacazes,RJ,72.19
1,2,00018f77f2f0320c557190d7a144bdd3,santa fe do sul,SP,259.83
2,3,000229ec398224ef6ca0657da4fc703e,para de minas,MG,216.87
3,4,00024acbcdf0a6daa1e931b038114c75,atibaia,SP,25.78
4,5,00042b26cf59d7ce69dfabb4e55b4fd9,varzea paulista,SP,218.04
5,6,00048cc3ae777c65dbb7d2a0634bc1ea,uberaba,MG,34.59
6,7,00054e8431b9d7675808bcb819fb4a32,guararapes,SP,31.75
7,8,000576fe39319847cbb9d288c5617fa6,praia grande,SP,880.75
8,9,0005a1a1728c9d785b8e2b08b904576c,santos,SP,157.60
9,10,0005f50442cb953dcd1d21e1fb923495,jandira,SP,65.39
10,11,00061f2a7bc09da83e415a52dc8a4af1,piracicaba,SP,68.87
11,12,00063b381e2406b52ad429470734ebd5,monte alto,SP,57.98
12,13,0006ec9db01a64e59a68b2c340bf65a7,rio de janeiro,RJ,97.32
13,14,0008288aa423d2a3f00fcb17cd7d8719,jandira,SP,63.27
14,15,0008288aa423d2a3f00fcb17cd7d8719,jandira,SP,63.27
15,16,0009792311464db532ff765bf7b182ae,alfenas,MG,127.55
16,17,0009c9a17f916a706d71784483a5d643,campinas,SP,650.34
17,18,000aed2e25dbad2f9ddb70584c5a2ded,santa barbara d'oeste,SP,152.77
18,19,000c3e6612759851cc3cbb4b83257986,jundiai,SP,112.71
19,20,000e562887b1f2006d75e0be9558292e,cubatao,SP,41.11

## Exercício 5 🟡 — INNER JOIN com produto e tempo

Mostre as vendas com **categoria do produto** e **mês/ano da venda**.

Use `INNER JOIN` entre:

- `fato_vendas` e `dim_produto`
- `fato_vendas` e `dim_tempo`

Mostre as colunas:

- `f.order_id`
- `p.product_category_name_english AS categoria`
- `t.ano_mes`
- `f.valor_total`

Mostre apenas 30 linhas.

**Objetivo:** praticar mais de um `JOIN` na mesma consulta.

In [9]:
banco_dados.sql("""
SELECT
    f.order_id,
    p.product_category_name_english AS categoria,
    t.ano_mes,
    f.valor_total
FROM fato_vendas f
INNER JOIN dim_produto p
    ON f.produto_sk = p.produto_sk
INNER JOIN dim_tempo t
    ON f.tempo_sk = t.tempo_sk
LIMIT 30;
""").df()

,order_id,categoria,ano_mes,valor_total
0,00010242fe8c5a6d1ba2dd792cb16214,cool_stuff,2017-09,72.19
1,00018f77f2f0320c557190d7a144bdd3,pet_shop,2017-04,259.83
2,000229ec398224ef6ca0657da4fc703e,furniture_decor,2018-01,216.87
3,00024acbcdf0a6daa1e931b038114c75,perfumery,2018-08,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,garden_tools,2017-02,218.04
5,00048cc3ae777c65dbb7d2a0634bc1ea,housewares,2017-05,34.59
6,00054e8431b9d7675808bcb819fb4a32,telephony,2017-12,31.75
7,000576fe39319847cbb9d288c5617fa6,garden_tools,2018-07,880.75
8,0005a1a1728c9d785b8e2b08b904576c,health_beauty,2018-03,157.60
9,0005f50442cb953dcd1d21e1fb923495,books_technical,2018-07,65.39
10,00061f2a7bc09da83e415a52dc8a4af1,health_beauty,2018-03,68.87
11,00063b381e2406b52ad429470734ebd5,fashion_bags_accessories,2018-07,57.98
12,0006ec9db01a64e59a68b2c340bf65a7,bed_bath_table,2018-07,97.32
13,0008288aa423d2a3f00fcb17cd7d8719,garden_tools,2018-02,63.27
14,0008288aa423d2a3f00fcb17cd7d8719,garden_tools,2018-02,63.27
15,0009792311464db532ff765bf7b182ae,sports_leisure,2018-08,127.55
16,0009c9a17f916a706d71784483a5d643,consoles_games,2018-04,650.34
17,000aed2e25dbad2f9ddb70584c5a2ded,perfumery,2018-05,152.77
18,000c3e6612759851cc3cbb4b83257986,sports_leisure,2017-08,112.71
19,000e562887b1f2006d75e0be9558292e,cool_stuff,2018-02,41.11
20,000e63d38ae8c00bbcb5a30573b99628,bed_bath_table,2018-03,56.78
21,000e906b789b55f64edcb1f84030f90d,telephony,2017-11,33.84
22,000f25f4d72195062c040b12dce9a18a,office_furniture,2018-03,164.39
23,001021efaa8636c29475e7734483457d,fashion_bags_accessories,2018-02,64.10
24,0010b2e5201cc5f1ae7e9c6cc8f5bd00,cool_stuff,2017-09,65.50
25,00119ff934e539cf26f92b9ef0cdfed8,sports_leisure,2017-08,236.88
26,0011d82c4b53e22e84023405fb467e57,luggage_accessories,2018-01,315.33
27,00125cb692d04887809806618a2a145f,furniture_decor,2017-03,135.41
28,00130c0eee84a3d909e75bc08c5c3ca1,food,2018-06,35.84
29,0013503b13da1eac686219390b7d641b,furniture_decor,2017-12,137.22

## Exercício 6 🟡 — Faturamento por estado

Calcule o **faturamento total por estado do cliente**.

Use `fato_vendas` e `dim_cliente`.

A consulta deve retornar:

- `estado`
- `qtd_pedidos`, contando pedidos únicos com `COUNT(DISTINCT f.order_id)`
- `faturamento_total`, usando `SUM(f.valor_total)`
- `ticket_medio`, usando `AVG(f.valor_total)`

Ordene pelo maior faturamento.

**Objetivo:** praticar `GROUP BY`, `SUM`, `COUNT`, `AVG` e `JOIN`.

In [10]:
banco_dados.sql("""
SELECT
    c.customer_state AS estado,
    COUNt(DISTINCT f.order_id) as qtd_pedidos,
    SUM(f.valor_total) AS faturamento_total,
    AVG(f.valor_total) as ticket_medio
FROM fato_vendas f
INNER JOIN dim_cliente c
    ON f.cliente_sk = c.cliente_sk
GROUP BY estado
ORDER BY faturamento_total DESC;
""").df()

   estado  qtd_pedidos  faturamento_total  ticket_medio
0      SP        40501         5769703.15    124.218549
1      RJ        12350         2055401.57    145.329956
2      MG        11354         1818891.67    140.824688
3      RS         5345          861472.79    140.442255
4      PR         4923          781708.80    138.380032
5      SC         3546          595127.78    145.259404
6      BA         3256          591137.81    160.504428
7      DF         2080          346123.35    146.973822
8      GO         1957          334212.35    146.777492
9      ES         1995          317657.93    142.767609
10     PE         1593          308972.05    176.959937
11     CE         1279          266436.77    186.842055
12     PA          946          212023.57    201.160882
13     MT          886          181224.42    174.758361
14     MA          717          147803.55    184.754438
15     PB          517          137838.55    235.219369
16     MS          701          134367.55    165.681319
17     PI          476          105178.19    201.105526
18     RN          474          100714.78    193.310518
19     AL          397           94172.49    220.544473
20     SE          335           70289.13    187.437680
21     TO          274           60007.37    193.572161
22     RO          243           56966.00    208.666667
23     AM          145           27585.47    169.236012
24     AC           80           19575.33    215.113516
25     AP           67           16141.81    199.281605
26     RR           41            9039.52    196.511304

## Exercício 7 🟡 — Receita por categoria somente em SP

Calcule a **receita por categoria de produto** considerando apenas clientes do estado de **SP**.

Use `fato_vendas`, `dim_produto` e `dim_cliente`.

A consulta deve retornar:

- `categoria`
- `qtd_pedidos`
- `receita_total`

Ordene pela maior receita.

**Objetivo:** praticar `WHERE` antes do `GROUP BY`.

In [11]:
banco_dados.sql("""
SELECT
    p.product_category_name AS categoria,
    COUNt(DISTINCT f.order_id) as qtd_pedidos,
    SUM(f.valor_total) AS receita_total,
FROM fato_vendas f
INNER JOIN dim_produto p
    ON f.produto_sk = p.produto_sk
INNER JOIN dim_cliente c
    ON f.cliente_sk = c.cliente_sk
WHERE c.customer_state = 'SP'
GROUP BY categoria
ORDER BY receita_total DESC;
""").df()

                        categoria  qtd_pedidos  receita_total
0                 cama_mesa_banho         4347      549061.89
1                    beleza_saude         3715      510255.38
2              relogios_presentes         2090      448582.76
3                   esporte_lazer         3216      428212.45
4          informatica_acessorios         2616      386280.65
..                            ...          ...            ...
68                casa_conforto_2           11         624.56
69                       pc_gamer            2         595.53
70                         flores           10         558.12
71              cds_dvds_musicais            6         409.64
72  fashion_roupa_infanto_juvenil            4         320.67

[73 rows x 3 columns]

## Exercício 8 🟠 — HAVING com pedidos por estado

Liste apenas os estados com **mais de 500 pedidos únicos**.

A consulta deve retornar:

- `estado`
- `qtd_pedidos`
- `receita_total`

Ordene do maior para o menor número de pedidos.

**Objetivo:** praticar filtro de grupos com `HAVING`.

In [12]:
banco_dados.sql("""
SELECT
    c.customer_state AS estado,
    COUNT(DISTINCT f.order_id) as qtd_pedidos,
    SUM(f.valor_total) AS receita_total,
FROM fato_vendas f
INNER JOIN dim_cliente c
    ON f.cliente_sk = c.cliente_sk
GROUP BY estado
HAVING qtd_pedidos > 500
ORDER BY qtd_pedidos DESC;    
""").df()

   estado  qtd_pedidos  receita_total
0      SP        40501     5769703.15
1      RJ        12350     2055401.57
2      MG        11354     1818891.67
3      RS         5345      861472.79
4      PR         4923      781708.80
5      SC         3546      595127.78
6      BA         3256      591137.81
7      DF         2080      346123.35
8      ES         1995      317657.93
9      GO         1957      334212.35
10     PE         1593      308972.05
11     CE         1279      266436.77
12     PA          946      212023.57
13     MT          886      181224.42
14     MA          717      147803.55
15     MS          701      134367.55
16     PB          517      137838.55

## Exercício 9 🟠 — Receita mensal com DATE_TRUNC

Calcule o **faturamento por mês** usando `DATE_TRUNC`.

Use `fato_vendas` e `dim_tempo`.

A consulta deve retornar:

- `mes_referencia`, usando `DATE_TRUNC('month', CAST(t.data AS DATE))`
- `qtd_pedidos`
- `receita_total`

Ordene pelo mês em ordem crescente.

**Objetivo:** praticar agregação temporal com `DATE_TRUNC`.

In [13]:
banco_dados.sql("""
SELECT
    DATE_TRUNC('month', CAST(t.data AS DATE)) AS mes_referencia,
    COUNT(DISTINCT f.order_id) as qtd_pedidos,
    SUM(f.valor_total) AS receita_total
FROM fato_vendas f
INNER JOIN dim_tempo t
    ON f.tempo_sk = t.tempo_sk
GROUP BY mes_referencia
ORDER BY mes_referencia ASC;
""").df()

   mes_referencia  qtd_pedidos  receita_total
0      2016-09-01            1         143.46
1      2016-10-01          265       46490.66
2      2016-12-01            1          19.62
3      2017-01-01          750      127482.37
4      2017-02-01         1653      271239.32
5      2017-03-01         2546      414330.95
6      2017-04-01         2303      390812.40
7      2017-05-01         3546      566851.40
8      2017-06-01         3135      490050.37
9      2017-07-01         3872      566299.08
10     2017-08-01         4193      645832.36
11     2017-09-01         4150      701077.49
12     2017-10-01         4478      751117.01
13     2017-11-01         7289     1153364.20
14     2017-12-01         5513      843078.29
15     2018-01-01         7069     1077887.46
16     2018-02-01         6555      966168.41
17     2018-03-01         7003     1120598.24
18     2018-04-01         6798     1132878.93
19     2018-05-01         6749     1128774.52
20     2018-06-01         6099     1011978.29
21     2018-07-01         6159     1027807.28
22     2018-08-01         6351      985491.64

## Exercício 10 🔴 — Desafio BI: sazonalidade por trimestre e categoria

Monte uma análise de **receita por trimestre e categoria**.

Use `fato_vendas`, `dim_produto` e `dim_tempo`.

A consulta deve retornar:

- `ano`, usando `EXTRACT(YEAR FROM CAST(t.data AS DATE))`
- `trimestre`, usando `EXTRACT(QUARTER FROM CAST(t.data AS DATE))`
- `categoria`
- `qtd_pedidos`
- `receita_total`
- `ticket_medio`

Mostre apenas grupos com `receita_total` acima de **50000**.

Ordene por:

1. `ano`
2. `trimestre`
3. `receita_total` do maior para o menor

**Objetivo:** combinar `JOIN`, `GROUP BY`, `EXTRACT`, `HAVING` e `ORDER BY`.

In [14]:
banco_dados.sql("""
SELECT 
    EXTRACT(YEAR FROM CAST(t.data AS DATE)) AS ano,
    EXTRACT(QUARTER FROM CAST(t.data AS DATE)) AS trimestre,
    p.product_category_name AS categoria,
    COUNT(f.order_id) AS qtd_pedidos,
    SUM(f.valor_total) AS receita_total,
    AVG(f.valor_total) AS ticket_medio
from fato_vendas f
INNER JOIN dim_produto p
    ON f.produto_sk = p.produto_sk
INNER JOIN dim_tempo t
    ON f.tempo_sk = t.tempo_sk
GROUP BY 
    EXTRACT(YEAR FROM CAST(t.data AS DATE)),
    EXTRACT(QUARTER FROM CAST(t.data AS DATE)),
    categoria
HAVING receita_total > 50000
ORDER BY ano, trimestre, receita_total DESC;
""").df()

,ano,trimestre,categoria,qtd_pedidos,receita_total,ticket_medio
0,2017,1,moveis_decoracao,749,68664.51,91.674913
1,2017,1,beleza_saude,444,68445.11,154.155653
2,2017,1,esporte_lazer,413,58618.11,141.932470
3,2017,1,cama_mesa_banho,482,52956.32,109.867884
4,2017,2,beleza_saude,718,114553.78,159.545655
...,...,...,...,...,...,...
91,2018,3,telefonia,492,71894.99,146.128028
92,2018,3,bebes,426,52849.88,124.060751
93,2018,3,perfumaria,417,52229.59,125.250815
94,2018,3,pet_shop,356,51492.38,144.641517
95,2018,3,ferramentas_jardim,313,50755.31,162.157540

## Checklist final

Antes de entregar, confira:

- Todas as consultas executaram sem erro.
- As consultas com `JOIN` usam as chaves corretas: `cliente_sk`, `produto_sk` e `tempo_sk`.
- As consultas agregadas usam `GROUP BY` para todas as colunas não agregadas.
- Filtros antes da agregação usam `WHERE`.
- Filtros depois da agregação usam `HAVING`.
- Os resultados estão ordenados conforme o enunciado.